[package]
name = "catgirl-engine-client"
license = "Zlib"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "~0.1", default-features = false, features = ["log"] }
winit = { version = "~0.29" }
wgpu = { version = "~0.19", default-features = false }
# egui = { version = "~0.26" }
# egui-wgpu = { version = "~0.26" }
image = { version = "~0.24" }

[target.'cfg(not(target_family="wasm"))'.dependencies]
wgpu = { version = "~0.19", default-features = true }
futures = { version = "~0.3", default-features = false, features = ["executor"] }

[target.'cfg(target_os="android")'.dependencies]
winit = { version = "~0.29", features = ["android-game-activity"] }

[target.'cfg(target_family="wasm")'.dependencies]
wgpu = { version = "~0.19", default-features = false, features = ["webgl"] }
wasm-bindgen-futures = { version = "~0.4", default-features = false }
futures-channel = { version = "~0.3", default-features = false }
