[package]
name = "catgirl-engine-client"
description = "Client side part of the catgirl-engine crate"
license = "Zlib"
version = "0.12.9"
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/lexi-the-cute/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine-client"
homepage = "https://github.com/lexi-the-cute/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@foxgirl.land>"]  # <@user@server> is a Fedi Address
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
build-info-build = { version = "^0.0.36", default-features = false }

[dependencies]
build-info = { version = "^0.0.36", default-features = false, features = ["runtime"] }
utils = { version = "0.12.9", package = "catgirl-engine-utils", path = "../utils" }
wasm-bindgen = { version = "~0.2", default-features = true }
tracing = { version = "~0.1", default-features = false, features = ["log"] }
winit = { version = "~0.29" }
wgpu = { version = "~0.19", default-features = false }
image = { version = "~0.24" }
# egui = { version = "~0.26" }
# egui-wgpu = { version = "~0.26" }

[target.'cfg(not(target_family="wasm"))'.dependencies]
wgpu = { version = "~0.19", default-features = true, features = ["fragile-send-sync-non-atomic-wasm"] }
futures = { version = "~0.3", default-features = false, features = ["executor"] }

[target.'cfg(target_os="android")'.dependencies]
winit = { version = "~0.29", features = ["android-game-activity"] }

[target.'cfg(target_family="wasm")'.dependencies]
wgpu = { version = "~0.19", default-features = false, features = ["webgl", "fragile-send-sync-non-atomic-wasm"] }
wasm-bindgen-futures = { version = "~0.4", default-features = false }
futures-channel = { version = "~0.3", default-features = false }
web-sys = { version = "~0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement"]}
