[package]
name = "catgirl-engine"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["browser", "client", "server"]
browser = []
client = ["dep:winit"]
server = []

[build-dependencies]
cc = "1.0.79"
cbindgen = "0.24.5"

[dependencies]
log = "0.4.19"
winit = { version="0.28.6", optional=true }

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "1.44.0"

[target.'cfg(any(unix,windows))'.dependencies]
pretty_env_logger = "0.5.0"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13.1"
