[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "All Rights Reserved (For Now)"
version = "0.1.0"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"

[lib]
name = "main"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.18.0"  # You can use * to tell Rust to pick a version
rand = "0.8.5"
rayon = "1.7.0"
log = "0.4.17"
android_logger = "0.13.1"
pretty_env_logger = "0.4.0"

[dependencies.sdl2]
git = "https://github.com/alexisart/rust-sdl2"
branch = "master"
default-features = false
features = ["image", "ttf"]  # bundled for cmake

[package.metadata.deb]
# This depends string is set based on what Github Actions compiles against
depends = "libc6 (>= 2.32),libsdl2-dev,libsdl2-image-dev,libsdl2-ttf-dev"
assets = [
    ["target/release/catgirl-engine", "/usr/games/", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]