[package]
name = "game"
version = "0.1.0"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"

[lib]
name = "main"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.18.0"  # You can use * to tell Rust to pick a version
rand = "0.8.5"
rayon = "1.7.0"

[dependencies.sdl2]
git = "https://github.com/alexisart/rust-sdl2"
branch = "master"
default-features = false
features = ["image", "ttf"]  # bundled for cmake