[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "All Rights Reserved (For Now)"
version = "0.3.0"  # https://semver.org/ (Do not use 1.0.0 until first production release)
categories = ["game-engines"]
repository = "https://github.com/alexisart/CatgirlEngine"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"

[lib]
name = "main"
crate-type = ["cdylib"]

[profile.release]
lto = true
debug = true
#panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.18.0"  # You can use * to tell Rust to pick a version
rand = "0.8.5"
rayon = "1.7.0"
log = "0.4.17"
android_logger = "0.13.1"
pretty_env_logger = "0.4.0"

[dependencies.sdl2]
git = "https://github.com/alexisart/rust-sdl2"
branch = "master"
default-features = false
features = ["image", "ttf"]  # hidapi at https://github.com/Rust-SDL2/rust-sdl2/blob/27cd1fd67c811e06b9d997a77bb6089a1b65070d/src/sdl2/lib.rs#L86

[package.metadata.deb]
depends = "$auto"
section = "games"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]