[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "Zlib"
version = "0.4.2"  # https://semver.org (Do not use 1.0.0 until first production release)
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/alexisart/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine"
homepage = "https://github.com/alexisart/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Fedi Address
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "main"
crate-type = ["cdylib", "rlib"]  # cdylib - C Compatible Lib, rlib - Rust Lib

[profile.release]
lto = true
debug = true  # Setting to false significantly reduces code size
#panic = "abort"

[features]
default = ["client", "server"]
client = ["dep:winit"]
server = []

[build-dependencies]
cc = "1.0.83"
cbindgen = "0.26.0"

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "2.0.4"

[dependencies]
cfg-if = "1.0.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
winit = { version = "0.29.10", optional = true }
wgpu = "0.19.1"
ctrlc = "3.4.2"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13.3"
winit = { version = "0.29.10", features = ["android-game-activity"] }

[package.metadata.deb]
name = "catgirl-engine"
provides = "catgirl-engine"
replaces = "catgirl-engine, catgirl-engine-server, catgirl-engine-client"
section = "games"
preserve-symlinks = true
depends = "$auto"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]

[package.metadata.deb.variants.server]
name = "catgirl-engine-server"
features = ["server"]
default-features = false