[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "Zlib"
version = "0.4.1"  # https://semver.org/ (Do not use 1.0.0 until first production release)
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/alexisart/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine"
homepage = "https://github.com/alexisart/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "main"
crate-type = ["cdylib", "rlib"]  # cdylib - C Compatible Lib, rlib - Rust Lib

[profile.release]
lto = true
debug = true  # Setting to false significantly reduces code size
#panic = "abort"

[features]
default = ["browser", "client", "server"]
browser = []
client = ["dep:winit"]
server = []

[workspace]
members = ["wasm_threads"]

[build-dependencies]
cc = "1.0.79"
cbindgen = "0.24.5"

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "1.44.0"

[dependencies]
cfg-if = "1.0.0"
log = "0.4.19"
pretty_env_logger = "0.5.0"
# winit = { version = "0.28.6", optional = true }
winit = { git = "https://github.com/alexisart/winit.git", rev = "45d6295", optional = true }
wgpu = "0.16.1"

[target.'cfg(not(target_family="wasm"))'.dependencies]
ctrlc = "3.4.0"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13.1"
# winit = { version = "0.28.6", features = ["android-game-activity"] }
winit = { git = "https://github.com/alexisart/winit.git", rev = "45d6295", features = ["android-game-activity"] }

[target.'cfg(any(all(target_arch="wasm32", target_os="unknown"), all(target_arch="wasm64", target_os="unknown")))'.dependencies]
wasm-bindgen = "0.2.87"
wasm_threads = { path = "wasm_threads" }
console_error_panic_hook = "0.1.7"
wgpu = { version = "0.16.1", features = ["webgl"]}
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "console",
    "Document",
    "Window",
    "Element"
]}

[package.metadata.deb]
name = "catgirl-engine"
provides = "catgirl-engine"
replaces = "catgirl-engine, catgirl-engine-server, catgirl-engine-client"
section = "games"
preserve-symlinks = true
depends = "$auto"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]

[package.metadata.deb.variants.server]
name = "catgirl-engine-server"
features = ["server"]
default-features = false