[package]
name = "game"
version = "0.1.0"
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"
# build = "build.rs"
build = false  # Disable Looking For External Build Script

[lib]
name = "main"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.18.0"  # You can use * to tell Rust to pick a version
rand = "0.8.5"
rayon = "1.7.0"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["image"]