[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "Zlib"
version = "0.5.0"  # https://semver.org (Do not use 1.0.0 until first production release)
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/lexi-the-cute/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine"
homepage = "https://github.com/lexi-the-cute/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@foxgirl.land>"]  # <@user@server> is a Fedi Address
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "main"
crate-type = ["cdylib", "rlib"]  # cdylib - C Compatible Lib, rlib - Rust Lib

# Optimize for faster build times
[profile.dev]
lto = false
debug = true
opt-level = 0
incremental = true

# Optimize for speed while still allowing debugging information
[profile.dev.package."*"]
debug = true
opt-level = 3
incremental = true

# Optimize for speed and remove debug information for size
[profile.release]
lto = true
debug = false  # Setting to false significantly reduces code size (last test was 286 MB to 13 MB)
opt-level = 3
incremental = false

[features]
default = ["client", "server"]
client = ["dep:client"]
server = ["dep:server"]
tracing-subscriber = ["dep:tracing-subscriber"]

# Used for customizing building of docs.rs binary
[package.metadata.docs.rs]
features = ["default"]

[workspace]
members = [
    "client",
    "server"
]

[build-dependencies]
cc = "~1.0"
cbindgen = "~0"

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "~2"

[dependencies]
client = { path = "client", optional = true }
server = { path = "server", optional = true }
cfg-if = "~1"
pretty_env_logger = "~0"
tracing = { version = "~0.1", features = ["log"] }
tracing-subscriber = { version = "~0.3", optional = true }
clap = { version = "~4", features = ["derive"] }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
ctrlc = "~3"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "~0.13"

[target.'cfg(target_arch="wasm32")'.dependencies]
console_error_panic_hook = "~0.1"
console_log = "~1"
wasm-bindgen = "~0.2"
wasm-bindgen-futures = "~0.4"
web-sys = { version = "~0.3", features = ["Document", "Window", "Element"] }
getrandom = { version = "~0.2", features = ["js"] }

[package.metadata.deb]
name = "catgirl-engine"
provides = "catgirl-engine"
replaces = "catgirl-engine, catgirl-engine-server, catgirl-engine-client"
section = "games"
preserve-symlinks = true
depends = "$auto"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]

[package.metadata.deb.variants.server]
name = "catgirl-engine-server"
features = ["server"]
default-features = false