[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "Zlib"
version = "0.4.4"  # https://semver.org (Do not use 1.0.0 until first production release)
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/lexi-the-cute/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine"
homepage = "https://github.com/lexi-the-cute/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@foxgirl.land>"]  # <@user@server> is a Fedi Address
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "main"
crate-type = ["cdylib", "rlib"]  # cdylib - C Compatible Lib, rlib - Rust Lib

[profile.release]
lto = true
debug = true  # Setting to false significantly reduces code size
#panic = "abort"

[features]
default = ["client", "server"]
client = ["dep:winit", "dep:wgpu", "dep:egui"]
server = []

# Used for customizing building of docs.rs binary
[package.metadata.docs.rs]
features = ["default"]

[build-dependencies]
cc = "1.0.83"
cbindgen = "0.26.0"

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "2.0.4"

[dependencies]
cfg-if = "1.0.0"
log = {version = "0.4.20", features = ["std", "serde"]}
pretty_env_logger = "0.5.0"
winit = { version = "0.29.10", optional = true, features = ["serde"] }
wgpu = { version = "0.19.1", optional = true }
egui = { version = "0.25.0", optional = true, features = ["serde", "persistence"] }
piccolo = "0.3.1"
ctrlc = "3.4.2"
serde_json = "1.0.113"
clap = "4.4.18"
toml-config = { version = "0.4.0" }  # features = ["serde-serialization"]

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13.3"
winit = { version = "0.29.10", features = ["serde", "android-game-activity"] }

[package.metadata.deb]
name = "catgirl-engine"
provides = "catgirl-engine"
replaces = "catgirl-engine, catgirl-engine-server, catgirl-engine-client"
section = "games"
preserve-symlinks = true
depends = "$auto"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]

[package.metadata.deb.variants.server]
name = "catgirl-engine-server"
features = ["server"]
default-features = false