[package]
name = "catgirl-engine"
description = "A game engine for cool moddability and procedurally generated data"
license = "Zlib"
version = "0.4.0"  # https://semver.org/ (Do not use 1.0.0 until first production release)
categories = ["game-engines"]
repository = "https://github.com/alexisart/CatgirlEngine"
# documentation = "https://docs.catgirl.land/engine"  # These docs don't exist yet at time of writing
authors = ["Alexis <@alexis@alexisart.me>"]  # <@user@server> is a Mastodon URL
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "main"
crate-type = ["cdylib"]

[profile.release]
lto = true
debug = true
#panic = "abort"

[features]
default = ["browser", "client", "server"]
browser = []
client = ["dep:winit"]
server = []

[build-dependencies]
cc = "1.0.79"
cbindgen = "0.24.5"

[dependencies]
log = "0.4.19"
pretty_env_logger = "0.5.0"
wasm-bindgen = "0.2.87"
# winit = { version = "0.28.6", optional = true }
winit = { git = "https://github.com/alexisart/winit.git", rev = "45d6295", optional = true }
# winit = { path = "../winit", optional = true }

[target.'cfg(not(target_family="wasm"))'.dependencies]
ctrlc = "3.4.0"

[target.'cfg(unix)'.build-dependencies]
cargo-deb = "1.44.0"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13.1"
# winit = { version = "0.28.6", features = ["android-game-activity"] }
winit = { git = "https://github.com/alexisart/winit.git", rev = "45d6295", features = ["android-game-activity"] }
# winit = { path = "../winit", features = ["android-game-activity"] }

[target.'cfg(target_family="wasm")'.dependencies]
web-sys = { version = "0.3.64", features = ["console"] }

[package.metadata.deb]
name = "catgirl-engine"
provides = "catgirl-engine"
replaces = "catgirl-engine, catgirl-engine-server, catgirl-engine-client"
section = "games"
preserve-symlinks = true
depends = "$auto"
assets = [
    ["target/release/catgirl-engine", "/usr/games/catgirl-engine", "755"],
    ["assets/*", "/var/games/catgirl-engine/assets", "644"],
]

[package.metadata.deb.variants.server]
name = "catgirl-engine-server"
features = ["server"]
default-features = false
