[package]
name = "catgirl-engine-server"
license = "Zlib"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "~0.1", default-features = false, features = ["log"] }
rhai = { version = "~1", default-features = false, features = ["serde"] }
