[package]
name = "catgirl-engine-utils"
description = "Server side part of the catgirl-engine crate"
license = "Zlib"
version = "0.0.1"
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/lexi-the-cute/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine-server"
homepage = "https://github.com/lexi-the-cute/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@foxgirl.land>"]  # <@user@server> is a Fedi Address
edition = "2021"

[build-dependencies]
build-info-build = { version = "^0.0.35", default-features = false }

[dependencies]
build-info = { version = "^0.0.35", default-features = false, features = ["runtime"] }
clap = { version = "~4", features = ["derive"] }
wasm-bindgen = { version = "~0.2", default-features = true }
