[package]
name = "catgirl-engine-utils"
description = "Utility crate for the catgirl-engine crate"
license = "Zlib"
version = "0.12.14"
keywords = ["catgirl", "engine", "gamedev", "game"]
categories = ["game-engines"]
repository = "https://github.com/lexi-the-cute/catgirl-engine.git"
documentation = "https://docs.rs/catgirl-engine-utils"
homepage = "https://github.com/lexi-the-cute/catgirl-engine"
readme = "ReadMe.md"
authors = ["Alexis <@alexis@foxgirl.land>"]  # <@user@server> is a Fedi Address
edition = "2021"

[features]
default = ["build-info"]
build-info = ["dep:build-info-build", "dep:build-info"]

# Used for customizing building of docs.rs binary
[package.metadata.docs.rs]
features = []
no-default-features = true

[build-dependencies]
build-info-build = { version = "^0.0.36", default-features = false, optional = true }

[dependencies]
build-info = { version = "^0.0.36", default-features = false, features = ["runtime"], optional = true }
clap = { version = "~4", features = ["derive"] }
wasm-bindgen = { version = "~0.2", default-features = true }
