name: Build For Android
run-name: ${{ github.actor }} is building for Android
on: [push]
jobs:
  Build-Android:
    runs-on: ubuntu-latest
    environment: Android
    env:
      DESIRED_API: 21
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # List Files
      # - name: Switch To Running Directory
      #   run: cd ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Install Dependencies
      - name: Update APT Package Manager
        run: sudo apt update
      # - name: Installing Base Packages Via APT
      #   run: sudo apt install wget sudo coreutils sed dpkg apt git
      - name: Install APT Packages
        run: sudo apt install gcc libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev unzip openjdk-17-jre-headless

      # Setup Packages
      - name: Setup Java Update Alternatives
        run: sudo update-alternatives --set java $JAVA_HOME/bin/java

      # Extract Keystore
      - name: Extract Keystore
        run: echo "${{ RELEASE_KEY }}" | base64 -d > ${{ ANDROID_RELEASE_KEY_PATH }}

      - name: Create Build Directory
        run: mkdir -p build

      # Install Rust
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/build/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/build/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/build/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      - name: Create Tools Directory
        run: mkdir -p tools

      # Download Android NDK
      - name: Download Android NDK
        run: wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O ${{ github.workspace }}/tools/ndk.zip

      # Unzip Android NDK
      - name: Unzip Android NDK
        run: unzip ${{ github.workspace }}/tools/ndk.zip -d ${{ github.workspace }}/tools/

      # Download Android SDK
      - name: Download Android SDK
        run: wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O ${{ github.workspace }}/tools/cmdlt.zip

      # Unzip Android SDK
      - name: Unzip Android SDK
        run: unzip ${{ github.workspace }}/tools/cmdlt.zip -d ${{ github.workspace }}/tools/

      # Auto-Accept Android SDK Licenses
      - name: Auto Accept Android SDK Licenses
        run: yes | ${{ github.workspace }}/tools/cmdline-tools/bin/sdkmanager --licenses --sdk_root=${{ github.workspace }}/tools

      # Download Desired Android API
      - name: Download Desired Android API
        run: ${{ github.workspace }}/tools/cmdline-tools/bin/sdkmanager --install "platforms;android-$DESIRED_API" --sdk_root=${{ github.workspace }}/tools

      # Add Build Targets
      - name: Add armv7 Android Build Target
        run: rustup target add armv7-linux-androideabi
      - name: Add aarch64 Android Build Target
        run: rustup target add aarch64-linux-android
      - name: Add i686 Android Build Target
        run: rustup target add i686-linux-android
      - name: Add x86_64 Android Build Target
        run: rustup target add x86_64-linux-android

      # ----------------------------------------
      # TODO: Get Rid Of This and Have Gradle Output Dependencies Instead
      - name: Build SDL
        run: ${{ github.workspace }}/tools/android-ndk-r25c/ndk-build NDK_PROJECT_PATH="${{ github.workspace }}/android/app/jni/SDL" APP_BUILD_SCRIPT="${{ github.workspace }}/android/app/jni/SDL/Android.mk" APP_PLATFORM="android-$DESIRED_API"
      - name: Build SDL_image
        run: ${{ github.workspace }}/tools/android-ndk-r25c/ndk-build NDK_PROJECT_PATH="${{ github.workspace }}/android/app/jni/SDL_image" APP_BUILD_SCRIPT="${{ github.workspace }}/android/app/jni/SDL_image/Android.mk" APP_PLATFORM="android-$DESIRED_API"
      # - name: Build freetype
      #   run: ${{ github.workspace }}/tools/android-ndk-r25c/ndk-build NDK_PROJECT_PATH="${{ github.workspace }}/android/app/jni/freetype" APP_BUILD_SCRIPT="${{ github.workspace }}/android/app/jni/freetype/Android.mk" APP_PLATFORM="android-$DESIRED_API"
      # - name: Build harfbuzz
      #   run: ${{ github.workspace }}/tools/android-ndk-r25c/ndk-build NDK_PROJECT_PATH="${{ github.workspace }}/android/app/jni/harfbuzz" APP_BUILD_SCRIPT="${{ github.workspace }}/android/app/jni/harfbuzz/Android.mk" APP_PLATFORM="android-$DESIRED_API"
      # - name: Build SDL_ttf
      #   run: ${{ github.workspace }}/tools/android-ndk-r25c/ndk-build NDK_PROJECT_PATH="${{ github.workspace }}/android/app/jni/SDL_ttf" APP_BUILD_SCRIPT="${{ github.workspace }}/android/app/jni/SDL_ttf/Android.mk" APP_PLATFORM="android-$DESIRED_API"

      # Make Directories For Dropping SDL Library Into
      - name: Make Deps Directory For aarch64
        run: mkdir -p ${{ github.workspace }}/target/aarch64-linux-android/release/deps
      - name: Make Deps Directory For armv7
        run: mkdir -p ${{ github.workspace }}/target/armv7-linux-androideabi/release/deps
      - name: Make Deps Directory For i686
        run: mkdir -p ${{ github.workspace }}/target/i686-linux-android/release/deps
      - name: Make Deps Directory For x86_64
        run: mkdir -p ${{ github.workspace }}/target/x86_64-linux-android/release/deps

      # Copy SDL Library Over To Corresponding Directories
      - name: Copy SDL Over To Deps Directory For aarch64
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL/libs/arm64-v8a/libSDL2.so ${{ github.workspace }}/target/aarch64-linux-android/release/deps/libSDL2.so
      - name: Copy SDL Over To Deps Directory For armv7
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL/libs/armeabi-v7a/libSDL2.so ${{ github.workspace }}/target/armv7-linux-androideabi/release/deps/libSDL2.so
      - name: Copy SDL Over To Deps Directory For i686
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL/libs/x86/libSDL2.so ${{ github.workspace }}/target/i686-linux-android/release/deps/libSDL2.so
      - name: Copy SDL Over To Deps Directory For x86_64
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL/libs/x86_64/libSDL2.so ${{ github.workspace }}/target/x86_64-linux-android/release/deps/libSDL2.so

      # Copy SDL_image Library Over To Corresponding Directories
      - name: Copy SDL_image Over To Deps Directory For aarch64
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL_image/libs/arm64-v8a/libSDL2_image.so ${{ github.workspace }}/target/aarch64-linux-android/release/deps/libSDL2_image.so
      - name: Copy SDL Over To Deps Directory For armv7
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL_image/libs/armeabi-v7a/libSDL2_image.so ${{ github.workspace }}/target/armv7-linux-androideabi/release/deps/libSDL2_image.so
      - name: Copy SDL Over To Deps Directory For i686
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL_image/libs/x86/libSDL2_image.so ${{ github.workspace }}/target/i686-linux-android/release/deps/libSDL2_image.so
      - name: Copy SDL Over To Deps Directory For x86_64
        run: cp -a ${{ github.workspace }}/android/app/jni/SDL_image/libs/x86_64/libSDL2_image.so ${{ github.workspace }}/target/x86_64-linux-android/release/deps/libSDL2_image.so
      # ----------------------------------------

      # Create config.toml File
      - name: Create config.toml File
        run: sed "s/{android-version}/$DESIRED_API/g" ${{ github.workspace }}/.cargo/config.toml.sample > ${{ github.workspace }}/.cargo/config.toml

      # Build Engine As Library
      - name: Build CatgirlEngine For aarch64
        run: cargo build --target aarch64-linux-android --release
      - name: Build CatgirlEngine For armv7
        run: cargo build --target armv7-linux-androideabi --release
      - name: Build CatgirlEngine For i686
        run: cargo build --target i686-linux-android --release
      - name: Build CatgirlEngine For x86_64
        run: cargo build --target x86_64-linux-android --release

      # Create Directories For Storing Engine in App
      - name: Create Directory To Store CatgirlEngine In App For aarch64
        run: mkdir -p ${{ github.workspace }}/android/app/src/main/jniLibs/arm64-v8a
      - name: Create Directory To Store CatgirlEngine In App For armv7
        run: mkdir -p ${{ github.workspace }}/android/app/src/main/jniLibs/armeabi-v7a
      - name: Create Directory To Store CatgirlEngine In App For i686
        run: mkdir -p ${{ github.workspace }}/android/app/src/main/jniLibs/x86
      - name: Create Directory To Store CatgirlEngine In App For x86_64
        run: mkdir -p ${{ github.workspace }}/android/app/src/main/jniLibs/x86_64

      # Copy Engine To App
      - name: Store CatgirlEngine In App For aarch64
        run: cp ${{ github.workspace }}/target/aarch64-linux-android/release/libmain.so ${{ github.workspace }}/android/app/src/main/jniLibs/arm64-v8a/libmain.so
      - name: Store CatgirlEngine In App For armv7
        run: cp ${{ github.workspace }}/target/armv7-linux-androideabi/release/libmain.so ${{ github.workspace }}/android/app/src/main/jniLibs/armeabi-v7a/libmain.so
      - name: Store CatgirlEngine In App For i686
        run: cp ${{ github.workspace }}/target/i686-linux-android/release/libmain.so ${{ github.workspace }}/android/app/src/main/jniLibs/x86/libmain.so
      - name: Store CatgirlEngine In App For x86_64
        run: cp ${{ github.workspace }}/target/x86_64-linux-android/release/libmain.so ${{ github.workspace }}/android/app/src/main/jniLibs/x86_64/libmain.so

      # Copy Assets To Android Src
      # - name: Create Assets Directory
      #   run: mkdir -p ${{ github.workspace }}/android/app/src/main/assets
      # - name: Copy ResourcePack To Assets Directory
      #   run: cp -R assets ${{ github.workspace }}/android/app/src/main/assets/resourcepack

      # Compile Program
      - name: Build Android App as APK (Release)
        run: cd android && ${{ github.workspace }}/android/gradlew assembleRelease

      - name: Build Android App as Bundle (Release)
        run: cd android && ${{ github.workspace }}/android/gradlew bundleRelease

      # Display APK Directory
      - name: Display APK Directory (Release)
        run: ls -liallh ${{ github.workspace }}/android/app/build/outputs/apk/release

      # Display Bundle Directory
      - name: Display Bundle Directory (Release)
        run: ls -liallh ${{ github.workspace }}/android/app/build/outputs/bundle/release

      # I may get rid of obfuscation/minifying, but until I decode on if I'll do that,
      #   I'm just releasing the mappings to make it easier for modders. Not that it'd help 
      #   on the engine itself as the engine is in Rust, not Java.

      # Upload APK
      - name: Upload APK (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Android
          path: |
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk
            ${{ github.workspace }}/android/app/build/outputs/mapping/release/mapping.txt

      # Upload Bundle
      - name: Upload Bundle (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Android
          path: |
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.aab
            ${{ github.workspace }}/android/app/build/outputs/mapping/release/mapping.txt

      # TODO: Upload to Play Store (and Github Releases) On Reading "Publish" in Commit Message

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."