name: Build For Windows x86_64
on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Run publish job'
        required: true
        default: 'no'
        type: choice
        options:
        - 'no'
        - 'yes'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Windows
    env:
      CARGO_TERM_COLOR: always
      WORKSPACE: ${{ github.workspace }}
      RUST_BACKTRACE: full
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install and Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-mingw-w64-x86-64-posix g++-mingw-w64-x86-64-posix wine64 # mingw-w64
          version: 1.0
          execute_install_scripts: true

      # Install Rust
      - name: Make Tools Directory
        run: mkdir -p ${{ github.workspace }}/tools
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/tools/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/tools/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/tools/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Toml Files Don't Take Variables, So We Have To Hardcode The File
      - name: Setup Config.toml
        run: sed "s:\$WORKSPACE:${{ github.workspace }}:g" ${{ github.workspace }}/.cargo/config.toml.sample > ${{ github.workspace }}/.cargo/config.toml

      # Install Rust Nightly Toolchains
      - name: Set Rust To The Nightly Toolchains
        run: $HOME/.cargo/bin/rustup default nightly

      # Setup Rust Build Caching
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "windows-rust-gnu-x86_64"

      # Add Build Targets
      - name: Add x86_64 GNU Windows Build Target
        run: $HOME/.cargo/bin/rustup target add x86_64-pc-windows-gnu

      # Install Git Pre-Commit Hooks to Enforce Hooks
      - name: Install Git Pre-Commit Hooks to Enforce Hooks
        run: pip install pre-commit

      # Check Pre-Commit Version
      - name: Check Pre-Commit Version
        run: pre-commit --version

      # Install Pre-Commit Hooks
      - name: Install Pre-Commit Hooks
        run: pre-commit install

      # Autoupdate Pre-Commit Hooks
      - name: Autoupdate Pre-Commit Hooks
        run: pre-commit autoupdate

      # Check Files with Pre-Commit Hooks
      - name: Check Files with Pre-Commit Hooks
        run: pre-commit run --all-files

      # Extract/Import GPG Signing Key
      - name: Extract GPG Signing Key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" > $HOME/signing.gpg
          gpg --import $HOME/signing.gpg

      # # Build Docs
      # - name: Build Docs
      #   run: |
      #     export RUSTFLAGS="-Z threads=`nproc --all`"
      #     $HOME/.cargo/bin/cargo doc -j `nproc --all` --target=x86_64-pc-windows-gnu --release --lib --workspace

      # Compile Program
      - name: Build Program
        run: |
          export RUSTFLAGS="-Z threads=`nproc --all` -Z self-profile"  # -Z time-passes
          $HOME/.cargo/bin/cargo build -j `nproc --all` --verbose --target=x86_64-pc-windows-gnu --release --bin catgirl-engine --timings

      # Display Export Directory
      - name: Display Export Directory
        run: ls -liallh ${{ github.workspace }}/target/x86_64-pc-windows-gnu/release

      # Prepare Artifact Uploads
      - name: Prepare Artifact Uploads
        run: |
          mkdir -p ${{ github.workspace }}/upload/profdata
          cp -a ${{ github.workspace }}/target/x86_64-pc-windows-gnu/release/*.exe ${{ github.workspace }}/upload
          #tar -cvf ${{ github.workspace }}/upload/docs.tar.gz ${{ github.workspace }}/target/x86_64-pc-windows-gnu/doc/
          cp -a ${{ github.workspace }}/target/binding ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/client/assets ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/target/cargo-timings ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/*.mm_profdata ${{ github.workspace }}/upload/profdata

      # Sign Files
      - name: Sign Files
        run: |
          cd ${{ github.workspace }}/upload
          find . -type f -not -name "checksums.sha512" -exec shasum -a 512 {} \; > checksums.sha512
          gpg --sign checksums.sha512

      # Upload Engine
      - name: Upload Engine (Release)
        uses: actions/upload-artifact@v4
        with:
          name: CatgirlEngine-Windows-x86_64-GNU-Zip
          path: ${{ github.workspace }}/upload/*

      # Test Minimal Dependency Versions
      # https://doc.rust-lang.org/cargo/reference/resolver.html
      # https://doc.rust-lang.org/cargo/reference/unstable.html?highlight=version#direct-minimal-versions
      - name: Test Minimal Dependency Versions
        continue-on-error: true
        run: |
          export RUSTFLAGS="-Z threads=`nproc --all`"
          $HOME/.cargo/bin/cargo build -j `nproc --all` --target=x86_64-pc-windows-gnu --bin catgirl-engine -Z direct-minimal-versions

      # Install Code Size Profiler
      - name: Install Code Size Profiler
        run: |
          export RUSTFLAGS="-Z threads=`nproc --all` -Z self-profile"  # -Z time-passes
          $HOME/.cargo/bin/cargo install -j `nproc --all` twiggy

      # Profile Code Size
      - name: Profile Code Size
        run: $HOME/.cargo/bin/twiggy top -n 20 "${{ github.workspace }}/target/x86_64-pc-windows-gnu/release/catgirl-engine.exe"

      # Install Miri
      # - name: Install Miri
      #   run: |
      #     rustup toolchain install nightly --component miri
      #     rustup override set nightly
      #     $HOME/.cargo/bin/cargo miri setup --target=x86_64-pc-windows-gnu

      # Run Miri Tests
      # - name: Run Miri Tests
      #   run: |
      #     # https://github.com/rust-lang/miri?tab=readme-ov-file#running-tests-in-parallel
      #     export RUSTFLAGS="-Z threads=`nproc --all`"
      #     $HOME/.cargo/bin/cargo miri test --workspace -j `nproc --all` --target=x86_64-pc-windows-gnu --bins --tests --benches --examples
      #     # $HOME/.cargo/bin/cargo miri nextest run -j`nproc --all`

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  run:
    if: ${{ success() }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Windows
    env:
      DISPLAY: :99
    steps:
      # Install Dependencies
      - name: Install and Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pipewire libgl1-mesa-dri xvfb icewm kde-spectacle libxkbcommon-x11-dev wine
          version: 1.0
          execute_install_scripts: true

      # Download Engine
      - name: Download Engine (Release)
        uses: actions/download-artifact@v4
        with:
          name: CatgirlEngine-Windows-x86_64-GNU-Zip
          path: ${{ github.workspace }}/artifacts/windows-x86_64

      # Start X Server
      - name: Start X Server and Window Manager
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 &
          icewm &

      # Run Game Engine
      - name: Run Game Engine
        run: |
          wine ${{ github.workspace }}/artifacts/windows-x86_64/catgirl-engine-* &
          sleep 30

      # Screenshot Game Engine
      - name: Screenshot Game Engine
        run: |
          mkdir -p ${{ github.workspace }}/upload
          spectacle -a -b -o ${{ github.workspace }}/upload/screenshot.png

      # Upload Screenshots
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: CatgirlEngine-Windows-x86_64-GNU-Screenshots-Zip
          path: ${{ github.workspace }}/upload/*

      # Kill Window Manager and X Server
      # - name: Kill Window Manager and X Server
      #   run: |
      #     killall wine
      #     killall Xvfb
      #     killall icewm

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  deploy:
    if: ${{ success() && (endsWith(github.event.head_commit.message, '--publish') || inputs.publish == 'yes') }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Windows
    env:
      BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
      GH_TOKEN: ${{ github.token }}
    permissions:
      # See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      # See https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens
      contents: write
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install and Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq  # coreutils gitsome
          version: 1.0
          execute_install_scripts: true

      # Download Engine
      - name: Download Engine (Release)
        uses: actions/download-artifact@v4
        with:
          name: CatgirlEngine-Windows-x86_64-GNU-Zip
          path: ${{ github.workspace }}/artifacts/windows-x86_64

      # Recreate Windows Zip
      - name: Recreate Windows Zip (Release)
        run: cd ${{ github.workspace }}/artifacts/windows-x86_64; zip -9 -y -r ../CatgirlEngine-Windows-x86_64.zip .

      # Create Tag and Github Release
      - name: 👩‍💻 Create Tag and Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export VERSION_STRING="Catgirl Engine v$VERSION"
          export BODY="Autogenerated Release From Github Actions..."

          export DRAFT="false"
          export PRERELEASE="false"
          export LATEST="true"
          export GENERATE_RELEASE_NOTES="true"

          export BRANCH=`git branch --show-current --format="%s" | tr -d '\n'`
          # export COMMIT=`git log -1 --oneline | cut -d' ' -f1 | tr -d '\n'`

          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases \
            -f tag_name="v$VERSION" \
            -f target_commitish="$BRANCH" \
            -f name="$VERSION_STRING" \
            -f body="$BODY" \
            -f make_latest="$LATEST" \
            -F draft="$DRAFT" \
            -F prerelease="$PRERELEASE" \
            -F generate_release_notes="$GENERATE_RELEASE_NOTES" || echo "Already Exists"

      # Publish to Github Release
      - name: 👩‍💻 Publish to Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export ARTIFACT_PATH="${{ github.workspace }}/artifacts/CatgirlEngine-Windows-x86_64.zip"
          export DISPLAY_LABEL="x86_64 Windows Zip"

          gh release upload v$VERSION "$ARTIFACT_PATH"#"$DISPLAY_LABEL" -R lexi-the-cute/catgirl-engine

      # Install Butler (For Uploading to Itch.io)
      - name: Install Butler (Upload to Itch.io)
        run: |
          # https://itch.io/docs/butler/pushing.html#channel-names
          # Setup For Installation
          mkdir -p ${{ github.workspace }}/tools/butler

          # Install Butler
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O ${{ github.workspace }}/butler-linux-amd64.zip
          unzip ${{ github.workspace }}/butler-linux-amd64.zip -d ${{ github.workspace }}/tools/butler

      # Publish to Itch.io
      - name: 🎮 Publish to Itch.io
        run: |
          # Upload App
          ${{ github.workspace }}/tools/butler/butler push ${{ github.workspace }}/artifacts/windows-x86_64 fomxgorl/catgirl-engine:windows-x86_64
