name: Test Variable
run-name: ${{ github.actor }} is testing Github Actions
on: [push]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    environment: Android
    steps:
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "ANDROID_RELEASE_KEY_PATH - ${{ vars.ANDROID_RELEASE_KEY_PATH }} | RUNNER_TEMP - $RUNNER_TEMP"