name: Build For Wasm 32-bit Web Browser
on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Run publish job'
        required: true
        default: 'no'
        type: choice
        options:
        - 'no'
        - 'yes'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: WebAssembly
    env:
      CARGO_TERM_COLOR: always
      WORKSPACE: ${{ github.workspace }}
      RUST_BACKTRACE: full
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Rust
      - name: Make Tools Directory
        run: mkdir -p ${{ github.workspace }}/tools
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/tools/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/tools/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/tools/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Install Rust Nightly Toolchains
      - name: Set Rust To The Nightly Toolchains
        run: $HOME/.cargo/bin/rustup default nightly

      # Setup Rust Build Caching
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "wasm32-rust"

      # Add Build Targets
      - name: Add 32-bit Wasm Build Target
        run: $HOME/.cargo/bin/rustup target add wasm32-unknown-unknown

      # Install Git Pre-Commit Hooks to Enforce Hooks
      - name: Install Git Pre-Commit Hooks to Enforce Hooks
        run: pip install pre-commit

      # Check Pre-Commit Version
      - name: Check Pre-Commit Version
        run: pre-commit --version

      # Install Pre-Commit Hooks
      - name: Install Pre-Commit Hooks
        run: pre-commit install

      # Autoupdate Pre-Commit Hooks
      - name: Autoupdate Pre-Commit Hooks
        run: pre-commit autoupdate

      # Check Files with Pre-Commit Hooks
      - name: Check Files with Pre-Commit Hooks
        run: pre-commit run --all-files

      # Extract/Import GPG Signing Key
      - name: Extract GPG Signing Key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" > $HOME/signing.gpg
          gpg --import $HOME/signing.gpg

      # # Build Docs
      # - name: Build Docs
      #   run: |
      #     export RUSTFLAGS="-Z threads=`nproc --all`"
      #     $HOME/.cargo/bin/cargo doc -j `nproc --all` --target=wasm32-unknown-unknown --release --lib --workspace

      # Install Wasm-Pack
      - name: Install Wasm-Pack
        run: |
          export RUSTFLAGS="-Z threads=`nproc --all` -Z self-profile"  # -Z time-passes
          $HOME/.cargo/bin/cargo install -j `nproc --all` wasm-pack

      # Copy License File
      - name: Copy License File
        run: |
          cp -a ${{ github.workspace }}/License.md ${{ github.workspace }}/LICENSE

      # Compile Program
      - name: Build Program
        run: |
          export RUSTFLAGS="-Z threads=`nproc --all` -Z self-profile"  # -Z time-passes
          $HOME/.cargo/bin/wasm-pack build --target web --verbose --release --bin catgirl-engine --timings

      # Display Export Directory
      - name: Display Export Directory
        run: ls -liallh ${{ github.workspace }}/target/wasm32-unknown-unknown/release

      # Prepare Artifact Uploads
      - name: Prepare Artifact Uploads
        run: |
          mkdir -p ${{ github.workspace }}/upload/profdata
          cp -a ${{ github.workspace }}/pkg ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/examples/wasm/web/index.html ${{ github.workspace }}/upload
          #tar -cvf ${{ github.workspace }}/upload/docs.tar.gz ${{ github.workspace }}/target/wasm32-unknown-unknown/doc/
          cp -a ${{ github.workspace }}/target/binding ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/client/assets ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/target/cargo-timings ${{ github.workspace }}/upload
          cp -a ${{ github.workspace }}/*.mm_profdata ${{ github.workspace }}/upload/profdata

      # Sign Files
      - name: Sign Files
        run: |
          cd ${{ github.workspace }}/upload
          find . -type f -not -name "checksums.sha512" -exec shasum -a 512 {} \; > checksums.sha512
          gpg --sign checksums.sha512

      # Upload Engine
      - name: Upload Engine (Release)
        uses: actions/upload-artifact@v4
        with:
          name: CatgirlEngine-Wasm-32-bit-Zip
          path: ${{ github.workspace }}/upload/*

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  run:
    if: ${{ success() }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: WebAssembly
    env:
      DISPLAY: :99
    steps:
      # Install Dependencies
      - name: Install and Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pipewire libgl1-mesa-dri xvfb icewm flameshot libxkbcommon-x11-dev python3 sudo snap
          version: 1.0
          execute_install_scripts: true

      # Install Snap Dependencies
      - name: Install Snap Dependencies
        run: |
          sudo snap install firefox

      # Download Engine
      - name: Download Engine (Release)
        uses: actions/download-artifact@v4
        with:
          name: CatgirlEngine-Wasm-32-bit-Zip
          path: ${{ github.workspace }}/artifacts/wasm-32-bit-web

      # Start X Server
      - name: Start X Server and Window Manager
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 &
          icewm &

      # Run Game Engine
      - name: Run Game Engine
        run: |
          cd ${{ github.workspace }}/artifacts/wasm-32-bit-web/
          python3 -m http.server 8000 &
          firefox http://localhost:8000 &

          sleep 30

      # Screenshot Game Engine
      - name: Screenshot Game Engine
        run: |
          mkdir -p ${{ github.workspace }}/upload
          #import -window "$(xdotool getactivewindow)" ${{ github.workspace }}/upload/screenshot.png  # X11
          flameshot screen -p ${{ github.workspace }}/upload/screenshot.png  # Wayland

      # Upload Screenshots
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: CatgirlEngine-Wasm-32-bit-Screenshots-Zip
          path: ${{ github.workspace }}/upload/*

      # Kill Window Manager and X Server
      # - name: Kill Window Manager and X Server
      #   run: |
      #     killall firefox
      #     killall python3
      #     killall Xvfb
      #     killall icewm

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  deploy:
    if: ${{ success() && (endsWith(github.event.head_commit.message, '--publish') || inputs.publish == 'yes') }}
    needs: [Run]
    runs-on: ubuntu-latest
    environment: WebAssembly
    env:
      BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
      GH_TOKEN: ${{ github.token }}
    permissions:
      # See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      # See https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens
      contents: write
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install and Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq  # coreutils gitsome
          version: 1.0
          execute_install_scripts: true

      # Download Engine
      - name: Download Engine (Release)
        uses: actions/download-artifact@v4
        with:
          name: CatgirlEngine-Wasm-32-bit-Zip
          path: ${{ github.workspace }}/artifacts/wasm-32-bit-web

      # Recreate Wasm Zip
      - name: Recreate Wasm Zip (Release)
        run: cd ${{ github.workspace }}/artifacts/wasm-32-bit-web; zip -9 -y -r ../CatgirlEngine-Wasm-32-bit-Web.zip .

      # Create Tag and Github Release
      - name: 👩‍💻 Create Tag and Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export VERSION_STRING="Catgirl Engine v$VERSION"
          export BODY="Autogenerated Release From Github Actions..."

          export DRAFT="false"
          export PRERELEASE="false"
          export LATEST="true"
          export GENERATE_RELEASE_NOTES="true"

          export BRANCH=`git branch --show-current --format="%s" | tr -d '\n'`
          # export COMMIT=`git log -1 --oneline | cut -d' ' -f1 | tr -d '\n'`

          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases \
            -f tag_name="v$VERSION" \
            -f target_commitish="$BRANCH" \
            -f name="$VERSION_STRING" \
            -f body="$BODY" \
            -f make_latest="$LATEST" \
            -F draft="$DRAFT" \
            -F prerelease="$PRERELEASE" \
            -F generate_release_notes="$GENERATE_RELEASE_NOTES" || echo "Already Exists"

      # Publish to Github Release
      - name: 👩‍💻 Publish to Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export ARTIFACT_PATH="${{ github.workspace }}/artifacts/CatgirlEngine-Wasm-32-bit-Web.zip"
          export DISPLAY_LABEL="32-bit Wasm Web Zip"

          gh release upload v$VERSION "$ARTIFACT_PATH"#"$DISPLAY_LABEL" -R lexi-the-cute/catgirl-engine

      # Install Butler (For Uploading to Itch.io)
      - name: Install Butler (Upload to Itch.io)
        run: |
          # https://itch.io/docs/butler/pushing.html#channel-names
          # Setup For Installation
          mkdir -p ${{ github.workspace }}/tools/butler

          # Install Butler
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O ${{ github.workspace }}/butler-linux-amd64.zip
          unzip ${{ github.workspace }}/butler-linux-amd64.zip -d ${{ github.workspace }}/tools/butler

      # Publish to Itch.io
      - name: 🎮 Publish to Itch.io
        run: |
          # Upload App
          ${{ github.workspace }}/tools/butler/butler push ${{ github.workspace }}/artifacts/wasm-32-bit-web fomxgorl/catgirl-engine:wasm-32-bit-web
