name: Build For Linux GNU x86_64
run-name: ${{ github.actor }} is building for Linux GNU x86_64
on: [push]
jobs:
  Build:
    runs-on: ubuntu-20.04
    environment: Linux
    env:
      CARGO_TERM_COLOR: always
      WORKSPACE: ${{ github.workspace }}
      RUST_BACKTRACE: full
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install APT Packages
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_on: error
          command: |
            sudo apt update
            sudo apt -y install gcc g++  # gcc-x86-64-linux-gnu g++-x86-64-linux-gnu

      # Install Rust
      - name: Make Tools Directory
        run: mkdir -p ${{ github.workspace }}/tools
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/tools/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/tools/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/tools/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Install Rust Stable Toolchains
      - name: Set Rust To The Stable Toolchains
        run: $HOME/.cargo/bin/rustup default stable

      # Setup Rust Build Caching
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "linux-rust-gnu-x86_64"

      # Add Build Targets
      - name: Add x86_64 GNU Build Target
        run: $HOME/.cargo/bin/rustup target add x86_64-unknown-linux-gnu

      # Install Code Size Profiler
      - name: Install Code Size Profiler
        run: $HOME/.cargo/bin/cargo install -j 4 twiggy

      # Compile Program
      - name: Build Program
        run: $HOME/.cargo/bin/cargo build -j 4 --verbose --target=x86_64-unknown-linux-gnu --bin catgirl-engine

      # Profile Code Size
      - name: Profile Code Size
        run: $HOME/.cargo/bin/twiggy top -n 20 "${{ github.workspace }}/target/x86_64-unknown-linux-gnu/debug/catgirl-engine"

      # Test Program
      - name: Test Program
        run: |
          # export LD_LIBRARY_PATH=${{ github.workspace }}/target/libs:$LD_LIBRARY_PATH
          $HOME/.cargo/bin/cargo test -j 4 --verbose --target=x86_64-unknown-linux-gnu --bins --tests --benches --examples

      # Display Export Directory
      - name: Display Export Directory
        run: ls -liallh ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/debug

      # Prepare Artifact Uploads
      - name: Prepare Artifact Uploads
        run: |
          mkdir -p ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/debug/catgirl-engine ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/client/assets ${{ github.workspace }}/upload

      # Upload Engine
      - name: Upload Engine (debug)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Linux-x86_64-GNU-Zip
          path: ${{ github.workspace }}/upload/*

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  Publish:
    if: ${{ success() && endsWith(github.event.head_commit.message, '--publish') }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Linux
    env:
      BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
      GH_TOKEN: ${{ github.token }}
    permissions:
      # See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      # See https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens
      contents: write
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install APT Packages
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_on: error
          command: |
            sudo apt update
            sudo apt -y install jq  # coreutils gitsome

      # Download Engine
      - name: Download Engine (debug)
        uses: actions/download-artifact@v3
        with:
          name: CatgirlEngine-Linux-x86_64-GNU-Zip
          path: ${{ github.workspace }}/artifacts/linux-gnu-x86_64

      # Recreate Windows Zip
      - name: Recreate Windows Zip (debug)
        run: cd ${{ github.workspace }}/artifacts/linux-gnu-x86_64; zip -9 -y -r ../CatgirlEngine-Linux-GNU-x86_64.zip .

      # Create Tag and Github debug
      - name: 👩‍💻 Create Tag and Github debug
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export VERSION_STRING="Catgirl Engine v$VERSION"
          export BODY="Autogenerated debug From Github Actions..."

          export DRAFT="false"
          export PREdebug="true"
          export GENERATE_debug_NOTES="true"

          export BRANCH=`git branch --show-current --format="%s" | tr -d '\n'`
          # export COMMIT=`git log -1 --oneline | cut -d' ' -f1 | tr -d '\n'`

          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/debugs \
            -f tag_name="v$VERSION" \
            -f target_commitish="$BRANCH" \
            -f name="$VERSION_STRING" \
            -f body="$BODY" \
            -F draft="$DRAFT" \
            -F predebug="$PREdebug" \
            -F generate_debug_notes="$GENERATE_debug_NOTES" || echo "Already Exists"

      # Publish to Github debug
      - name: 👩‍💻 Publish to Github debug
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export ARTIFACT_PATH="${{ github.workspace }}/artifacts/linux-gnu-x86_64/catgirl-engine_x86_64"
          export DISPLAY_LABEL="x86_64"

          gh debug upload v$VERSION "$ARTIFACT_PATH"#"$DISPLAY_LABEL" -R lexi-the-cute/catgirl-engine

      # Install Butler (For Uploading to Itch.io)
      - name: Install Butler (Upload to Itch.io)
        run: |
          # https://itch.io/docs/butler/pushing.html#channel-names
          # Setup For Installation
          mkdir -p ${{ github.workspace }}/tools/butler

          # Install Butler
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O ${{ github.workspace }}/butler-linux-amd64.zip
          unzip ${{ github.workspace }}/butler-linux-amd64.zip -d ${{ github.workspace }}/tools/butler

      # Publish to Itch.io
      - name: 🎮 Publish to Itch.io
        run: |
          # Upload App
          ${{ github.workspace }}/tools/butler/butler push ${{ github.workspace }}/artifacts/linux-gnu-x86_64 catgirlland/catgirl-engine:linux-gnu-x86_64
