name: Build For Linux (Deb)
run-name: ${{ github.actor }} is building for Linux (Deb)
on: [push]
jobs:
  Build-Linux-Debian:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # List Files
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Install Dependencies
      - name: Update APT Package Manager
        run: sudo apt update
      - name: Install APT Packages
        run: sudo apt -y install gcc g++ binutils musl-tools
      # - name: Install SDL Packages
      #   run: sudo apt -y install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      # Symlink g++ to musl-g++
      - name: Install SDL Packages
        run: sudo ln -s /bin/g++ /bin/musl-g++

      - name: Create Build Directory
        run: mkdir -p build

      # Install Rust
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/build/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/build/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/build/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      - name: Add x86_64 Musl Build Target
        run: $HOME/.cargo/bin/rustup target add x86_64-unknown-linux-musl

      # Install Deb Packager
      - name: Install Deb Packager
        run: $HOME/.cargo/bin/cargo install cargo-deb

      # Compile Program (Testing)
      - name: Build Program (Release)
        run: RUST_BACKTRACE=full $HOME/.cargo/bin/cargo build --release --target=x86_64-unknown-linux-musl --features bundled --bin catgirl-engine  # --separate-debug-symbols

      # Compile Program
      - name: Build Program (Deb)
        run: RUST_BACKTRACE=full $HOME/.cargo/bin/cargo deb --target=x86_64-unknown-linux-musl  # --separate-debug-symbols

      - name: Test Program
        run: |
          RUST_BACKTRACE=full $HOME/.cargo/bin/cargo test --verbose --target=x86_64-unknown-linux-musl --bins --tests --benches --examples

      # Display Export Directory
      - name: Display Export Directory
        run: ls -liallh ${{ github.workspace }}/target/debian

      # Upload Engine
      - name: Upload Engine (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Linux-x86_64-Deb
          path: |
            ${{ github.workspace }}/target/debian/*.deb

      # TODO: Upload to Itch.io (and Github Releases) On Reading "Publish" in Commit Message

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."