name: Build For Android
run-name: ${{ github.actor }} is building for Android
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Android
    env:
      ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}
      ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
      ANDROID_RELEASE_KEY_PATH: ${{ vars.ANDROID_RELEASE_KEY_PATH }}
      ANDROID_HOME: /usr/local/lib/android/sdk
      CARGO_TERM_COLOR: always
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Gradle Build Action (For Caching Builds) - ./app/.cxx|./app/build|./.gradle
      - name: Setup Gradle Build Action (For Caching Builds)
        uses: gradle/gradle-build-action@v2

      # Setup Rust Build Caching
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "android-rust"

      # Install Dependencies
      - name: Install APT Packages
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_on: error
          command: |
            sudo apt update
            sudo apt -y install unzip

      # Extract Keystore
      - name: Extract Keystore
        run: echo "${{ secrets.RELEASE_KEY }}" | base64 -d > ${{ vars.ANDROID_RELEASE_KEY_PATH }}

      # Install Rust
      - name: Make Tools Directory
        run: mkdir -p ${{ github.workspace }}/tools
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/tools/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/tools/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/tools/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Install Rust Nightly Toolchains
      - name: Set Rust To The Nightly Toolchains
        run: $HOME/.cargo/bin/rustup default nightly

      # Add Build Targets
      - name: Add armv7 Android Build Target
        run: $HOME/.cargo/bin/rustup target add armv7-linux-androideabi
      - name: Add aarch64 Android Build Target
        run: $HOME/.cargo/bin/rustup target add aarch64-linux-android
      - name: Add i686 Android Build Target
        run: $HOME/.cargo/bin/rustup target add i686-linux-android
      - name: Add x86_64 Android Build Target
        run: $HOME/.cargo/bin/rustup target add x86_64-linux-android

      # Install Cargo-NDK
      - name: Install Cargo-NDK
        run: cargo install cargo-ndk

      # Workaround Cargo Gradle Plugin Bug
      - name: Workaround Cargo Gradle Plugin Bug
        run: touch ${{ github.workspace }}/android/local.properties

      # Build Engine As APK
      - name: Build CatgirlEngine APK
        working-directory: ${{ github.workspace }}/android
        run: ${{ github.workspace }}/android/gradlew assembleRelease

      # Build Engine As AAB
      - name: Build CatgirlEngine AAB
        working-directory: ${{ github.workspace }}/android
        run: ${{ github.workspace }}/android/gradlew bundleRelease

      # Display APK Directory
      - name: Display APK Directory (Release)
        run: ls -liallh ${{ github.workspace }}/android/app/build/outputs/apk/release

      # Display Bundle Directory
      - name: Display Bundle Directory (Release)
        run: ls -liallh ${{ github.workspace }}/android/app/build/outputs/bundle/release

      # Prepare Artifact Uploads
      - name: Prepare Artifact Uploads
        run: |
          mkdir -p ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/android/app/build/outputs/bundle/release/app-release.aab ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/android/app/build/outputs/mapping/release/mapping.txt ${{ github.workspace }}/upload
          mv ${{ github.workspace }}/target/binding ${{ github.workspace }}/upload

      # Upload APK
      - name: Upload APK (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Android-APK
          path: |
            ${{ github.workspace }}/upload/app-release.apk
            ${{ github.workspace }}/upload/mapping.txt
            ${{ github.workspace }}/upload/binding

      # Upload Bundle
      - name: Upload Bundle (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Android-Bundle
          path: |
            ${{ github.workspace }}/upload/app-release.aab
            ${{ github.workspace }}/upload/mapping.txt
            ${{ github.workspace }}/upload/binding

      # List Environment
      - name: List Environment
        run: env
      - name: List All Installed Packages
        run: |
          apt list --installed | wc -l
          apt list --installed
      - name: List All Files
        run: find ${{ github.workspace }}

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."
  Publish:
    if: ${{ success() && endsWith(github.event.head_commit.message, '--publish') }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Android
    env:
      BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
      GH_TOKEN: ${{ github.token }}
    permissions:
      # See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      # See https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens
      contents: write
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Install Dependencies
      - name: Install APT Packages
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_on: error
          command: |
            sudo apt update
            sudo apt -y install ruby-bundler jq  # coreutils gitsome

      # Download APK
      - name: Download APK (Release)
        uses: actions/download-artifact@v3
        with:
          name: CatgirlEngine-Android-APK
          path: ${{ github.workspace }}/artifacts/apk

      # Download Bundle
      - name: Download Bundle (Release)
        uses: actions/download-artifact@v3
        with:
          name: CatgirlEngine-Android-Bundle
          path: ${{ github.workspace }}/artifacts/bundle

      # Recreate APK Zip
      - name: Recreate APK Zip (Release)
        run: cd ${{ github.workspace }}/artifacts/apk; zip -9 -y -r ../CatgirlEngine-Android-APK.zip .

      # Create Tag and Github Release
      - name: 👩‍💻 Create Tag and Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export VERSION_STRING="Catgirl Engine v$VERSION"
          export BODY="Autogenerated Release From Github Actions..."

          export DRAFT="false"
          export PRERELEASE="true"
          export GENERATE_RELEASE_NOTES="true"

          export BRANCH=`git branch --show-current --format="%s" | tr -d '\n'`
          # export COMMIT=`git log -1 --oneline | cut -d' ' -f1 | tr -d '\n'`

          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases \
            -f tag_name="v$VERSION" \
            -f target_commitish="$BRANCH" \
            -f name="$VERSION_STRING" \
            -f body="$BODY" \
            -F draft="$DRAFT" \
            -F prerelease="$PRERELEASE" \
            -F generate_release_notes="$GENERATE_RELEASE_NOTES" || echo "Already Exists"

      # Publish to Github Release
      - name: 👩‍💻 Publish to Github Release
        run: |
          export VERSION=`cat ${{ github.workspace }}/Cargo.toml | grep '^version' | head -n1 | cut -d'"' -f2 | tr -d '\n'`
          export ARTIFACT_PATH="${{ github.workspace }}/artifacts/CatgirlEngine-Android-APK.zip"
          export DISPLAY_LABEL="Android APK"

          gh release upload v$VERSION "$ARTIFACT_PATH"#"$DISPLAY_LABEL" -R alexisart/catgirl-engine

      # Setup Google Play Services Config
      - name: Setup Google Play Services Config
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_CONFIG }}" > ${{ github.workspace }}/android/google_play_service_account_config.json.base64
          base64 -d -i ${{ github.workspace }}/android/google_play_service_account_config.json.base64 > ${{ github.workspace }}/android/google_play_service_account_config.json
          rm ${{ github.workspace }}/android/google_play_service_account_config.json.base64

      # Install Fastlane (For Uploading to Play Store)
      - name: Install Fastlane (Upload to Play Store)
        working-directory: android
        run: |
          # https://docs.fastlane.tools/getting-started/android/screenshots/
          sudo gem install bundler -NV  # No documentation, yes verbose
          sudo bundle install

      # Publish to Play Store
      - name: 🏬 Publish to Play Store
        working-directory: android
        continue-on-error: true
        run: |
          bundle exec fastlane supply init --track internal
          bundle exec fastlane android internal

      # Install Butler (For Uploading to Itch.io)
      - name: Install Butler (Upload to Itch.io)
        run: |
          # https://itch.io/docs/butler/pushing.html#channel-names
          # Setup For Installation
          mkdir -p ${{ github.workspace }}/tools/butler

          # Install Butler
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O ${{ github.workspace }}/butler-linux-amd64.zip
          unzip ${{ github.workspace }}/butler-linux-amd64.zip -d ${{ github.workspace }}/tools/butler

      # Publish to Itch.io
      - name: 🎮 Publish to Itch.io
        run: |
          # Upload App
          ${{ github.workspace }}/tools/butler/butler push ${{ github.workspace }}/artifacts/apk/app-release.apk catgirlland/catgirl-engine:android