name: Build For Linux
run-name: ${{ github.actor }} is building for Linux
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # List Files
      # - name: Switch To Running Directory
      #   run: cd ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Install Dependencies
      - name: Update APT Package Manager
        run: sudo apt update
      # - name: Installing Base Packages Via APT
      #   run: sudo apt install sudo coreutils apt git
      - name: Install APT Packages
        run: sudo apt install gcc libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev zip musl-tools

      - name: Create Build Directory
        run: mkdir -p build

      # Install Rust
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${{ github.workspace }}/build/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ${{ github.workspace }}/build/rust.sh
      - name: Install Rust
        run: ${{ github.workspace }}/build/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Build SDL2
      - name: Switch to SDL2 Directory
        run: cd ${{ github.workspace }}/android/app/jni/SDL
      - name: Autogen SDL2
        run: ${{ github.workspace }}/autogen
      - name: Configure SDL2
        run: CC=/usr/bin/musl-gcc ${{ github.workspace }}/configure
      - name: Make SDL2
        run: make

      # Build SDL_image
      - name: Switch to SDL_image Directory
        run: cd ${{ github.workspace }}/android/app/jni/SDL_image
      - name: Autogen SDL_image
        run: ${{ github.workspace }}/autogen
      - name: Configure SDL_image
        run: CC=/usr/bin/musl-gcc ${{ github.workspace }}/configure
      - name: Make SDL_image
        run: make

      # Build SDL_image
      - name: Switch to SDL_ttf Directory
        run: cd ${{ github.workspace }}/android/app/jni/SDL_ttf
      - name: Autogen SDL_ttf
        run: ${{ github.workspace }}/autogen
      - name: Configure SDL_ttf
        run: CC=/usr/bin/musl-gcc ${{ github.workspace }}/configure
      - name: Make SDL_ttf
        run: make

      # Compile Program
      - name: Build Program (Release)
        run: cargo build --release --target x86_64-unknown-linux-musl --bin game

      # Display Build Directory
      - name: Display Built Program Directory (Release)
        run: ls -liallh ${{ github.workspace }}/target/x86_64-unknown-linux-musl/release

      # Copy To Root Of Project
      - name: Copy Game To Root For Zipping Up
        run: cp ${{ github.workspace }}/target/x86_64-unknown-linux-musl/release/game ${{ github.workspace }}

      # Zip Up Game and Assets
      # - name: Zip Up Game and Assets
      #   run: zip -9 -r ${{ github.workspace }}/CatgirlEngine.zip ${{ github.workspace }}/assets ${{ github.workspace }}/game

      # Upload Engine
      - name: Upload Engine (Release)
        uses: actions/upload-artifact@v3
        with:
          name: CatgirlEngine-Linux
          path: |
            ${{ github.workspace }}/game
            ${{ github.workspace }}/assets

      # TODO: Upload to Itch.io (and Github Releases) On Reading "Publish" in Commit Message

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."