name: Build For Linux
run-name: ${{ github.actor }} is building for Linux
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      # Setup Build Environment
      - name: 🎉 The job was automatically triggered by a ${{ github.event_name }} event.
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 💡 The ${{ github.repository }} repository has been cloned to the runner.
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # List Files
      # - name: Switch To Running Directory
      #   run: cd ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Install Dependencies
      - name: Update APT Package Manager
        run: sudo apt update
      # - name: Installing Base Packages Via APT
      #   run: sudo apt install sudo coreutils
      - name: Install APT Packages
        run: sudo apt install git gcc libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Create Build Directory
        run: mkdir -p build

      # Install Rust
      - name: Download Rust Installer
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./build/rust.sh
      - name: Make Rust Installer Executable
        run: chmod +x ./build/rust.sh
      - name: Install Rust
        run: ./build/rust.sh -y
      - name: Load Cargo Environment
        run: source "$HOME/.cargo/env"

      # Compile Program
      - name: Build Program
        run: cargo build --release

      # Display Build Directory
      - name: Display Built Program Directory (Release)
        run: ls -liallh ./target/release

      # Display Build Status
      - name: 🍏 This job's status is ${{ job.status }}.
        run: echo "🍏 This job's status is ${{ job.status }}."